module.exports={
    db_name:'focuspoint-shop',
    userCollection:'users1',
    adminCollection:'admin',
    productCollection:'guns',
    categoryCollection:'guns_category',
    cartCollection:'userCart',
    addressCollection:'Address',
    ordersCollection:'orders',
    coupenCollection:'coupons',
    wishlistCollection:'wishlist',
    walletCollection:'wallet',
}